### ISSUE TITLE
wetland indicator status feature

### ISSUE THREAD

**Issue by davereinhart** [sckott/usdaplantsapi#14]
This is a great API!  Would it be possible to add wetland indicators (indicator, region, and subregion) to the response?  That data can be queried here : https://plants.sc.egov.usda.gov/core/wetlandSearch

It's currently only available for querying and viewing, not downloading, so having it included in this API would be a huge time saver.

**Comment by sckott** [comment]
Thanks for the issue @geomapdev 

There is apparently a USDA made API for plants database. see https://drive.google.com/file/d/0B63q9uSv12TbNHJFX3I1VVE5Q2pWZFhtaUk4ZWlLRk5BOGlZ/view - Can you get it from that API? 

I"m not sure if I can get that wetland data. If I can, I'd be hesitant to combine it with what data I have now, since the data is from 2016. Let me know if the other API has the data
